name: Golden

on:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout and Setup
        uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: "flutter-:os:-:channel:-:version:-:arch:-:hash:"
          cache-path: "${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:"

      - run: flutter --version

      - name: Get dependencies
        run: |
          flutter pub get

      - name: Delete existing screenshots
        run: |
          chmod +x ./scripts/delete_screenshots.sh
          ./scripts/delete_screenshots.sh

      - name: Generate screenshots
        run: flutter test -t "golden" --update-goldens

      - name: Generate screenshots markdown document
        run: |
          chmod +x ./scripts/update_screenshots.sh
          ./scripts/update_screenshots.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: |
            screenshots/app_screenshots.md
            test/**/*_golden_*.png
